#!/bin/bash

#$ -S /bin/bash
#$ -o /wynton/home/degradolab/nick.polizzi/Combs2/designs/apixaban/20210922/logfiles
#$ -e /wynton/home/degradolab/nick.polizzi/Combs2/designs/apixaban/20210922/logfiles
#$ -cwd
#$ -r y
#$ -j y
#$ -l mem_free=8G
#$ -l hostname="qb3*&!qb3-ad*&!*gpu*"
#$ -l h_rt=08:00:00
#$ -t 1-1201

###################################
# number of task ids for HPC = (number of CG groups in ligand.txt) x 5 ABPLE x 20 AAs
###################################

export OMP_NUM_THREADS=1

# Anything under here can be a bash script

# If you used the -t option above, this same script will be run for each task,
# but with $SGE_TASK_ID set to a different value each time (1-10 in this case).
# The commands below are one way to select a different input (PDB codes in
# this example) for each task.  Note that the bash arrays are indexed from 0,
# while task IDs start at 1, so the first entry in the tasks array variable
# is simply a placeholder

date
hostname

ind=$SGE_TASK_ID

conda activate env_combs
db_path=/wynton/scratch/nick.polizzi/comb/vdMs/
inpath=/wynton/home/degradolab/nick.polizzi/Combs2/designs/apixaban/20210922
ligtxt=$inpath/ligand.txt
ligpdb=$inpath/GG2.pdb
ligparams=$inpath/GG2.params
ligrn=GG2
removehbdict=$inpath/remove_hb.txt
hbonly=False
superposetype=enriched
superpose_rn_file=$inpath/superpose_resname.txt
outpath=/wynton/scratch/nick.polizzi/comb/lig_vdMs/apixaban/

python /wynton/home/degradolab/nick.polizzi/Combs2/combs2/programs/run_superpose_lig.py  --i=$ind --o=$outpath --d=$db_path --lig_txt=$ligtxt --lig_pdb=$ligpdb --lig_params=$ligparams --lig_resname=$ligrn --remove_atoms_from_hb_dict=$removehbdict --hb_only=$hbonly --superpose_type=$superposetype --superpose_resnames_file=$superpose_rn_file

qstat -j $JOB_ID                                  # This is useful for debugging and usage purposes,
                                                  # e.g. "did my job exceed its memory request?"
